name: Deploy staging

on:
  push:
    branches: [main]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - uses: pnpm/action-setup@v4
        with:
          version: 10.32.1
          run_install: false

      - uses: ./.github/actions/smart-vercel
        name: Deploy to Vercel
        with:
          node_version: 22
          vercel_token: ${{ secrets.VERCEL_TOKEN }}
          vercel_group: itering
          preview_output: true
          project_name: degov-home
          dist_path: out
          script_install: pnpm install --frozen-lockfile
          script_build: pnpm build
          enable_notify_slack: false
          slack_channel: public-degov
          slack_webhook: ${{ secrets.SLACK_INCOMING_WEBHOOK_URL }}
